### ISSUE TITLE
Issue: "document is not defined", Solution: use "@jest-environment jsdom jsdom"

### ISSUE THREAD

**Issue by dxps** [basarbk/tdd-svelte#1]
Hi Basar,

Thanks for the course! :pray: I just started watching it, and faced a small issue in the _Introduction_ chapter.
I am assuming that things changed meanwhile, as it generally happens in the JS world.
Please find below the issue and how it was solved.
I hope it helps others as well.

![image](https://user-images.githubusercontent.com/14140226/150766909-3cf82a29-e65b-4bab-8082-ef65639ba7c5.png)

`package.json` file content being:
```json
{
  "name": "svelte-app",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "rollup -c",
    "dev": "rollup -c -w",
    "start": "sirv public --no-clear",
    "test": "jest --watch"
  },
  "devDependencies": {
    "@babel/preset-env": "^7.16.11",
    "@rollup/plugin-commonjs": "^17.0.0",
    "@rollup/plugin-node-resolve": "^11.0.0",
    "@testing-library/jest-dom": "^5.16.1",
    "@testing-library/svelte": "^3.0.3",
    "@testing-library/user-event": "^13.5.0",
    "babel-jest": "^27.4.6",
    "jest": "^27.4.7",
    "rollup": "^2.3.4",
    "rollup-plugin-css-only": "^3.1.0",
    "rollup-plugin-livereload": "^2.0.0",
    "rollup-plugin-svelte": "^7.0.0",
    "rollup-plugin-terser": "^7.0.0",
    "svelte": "^3.0.0",
    "svelte-jester": "^2.1.5"
  },
  "dependencies": {
    "sirv-cli": "^2.0.0"
  },
  "jest": {
    "transform": {
      "^.+\\.svelte$": "svelte-jester",
      "^.+\\.js$": "babel-jest"
    }
  }
}
```

Following the test result provided [link](https://jestjs.io/docs/configuration#testenvironment-string), I just added the `@jest-environment` _docblock_ at the beginning of the test file, and all went fine:

![image](https://user-images.githubusercontent.com/14140226/150770250-a0c399e0-428b-404f-8fd5-39b44e2b40b7.png)

So now the `SignUpPage.spec.js` looks like this:

```js
/**
 * @jest-environment jsdom
 */

import SignUpPage from './SignUpPage.svelte'
import { render, screen } from '@testing-library/svelte';
import "@testing-library/jest-dom";

it('has Sign Up header', () => {
    render(SignUpPage);
    const header = screen.getByRole('heading', { name: 'Sign Up' });
    // Check if it has any value.
    expect(header).toBeInTheDocument();
});
```

If it's all good, the issue can be closed and remain as a future reference.

**Comment by basarbk** [comment]
Hi @dxps 
Thanks for sharing this.
The default behavior is changed with jest version 27.
Just like you did in test module you can specifiy the environment. or you can set it as global configuration for jest as follows

```js
{ // package.json
  //...
  "jest": {
    "transform": {
      "^.+\\.svelte$": "svelte-jester",
      "^.+\\.js$": "babel-jest"
    },
    // setting the environment to jsdom here
    "testEnvironment": "jsdom"
  }
}
```
